name: Test and update coverage badge

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Remove dist directory
        run: rm -rf dist
      - name: Run tests with coverage
        run: npm test -- --coverage --coverageReporters="text-summary" --coverageReporters="json-summary"
      - name: Generate coverage badge
        run: node scripts/generateCoverageBadge.cjs
      - name: Commit coverage badge
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .github/badges/coverage.json
          if git commit -m "chore: update coverage badge"; then
            git push
          fi
